### ISSUE TITLE
Add v2 functionality of Invite-Settings Tab

### ISSUE THREAD

**Issue by eburck** [trustedshops-public/connect-app-demo#69]
### Description

New functionality of connector / eventslib should be reflected in Demo-App as well:

- add switch to v2 at informationOfSystem
- add reasonable test data for available order statuses
- add reasonable test data for set order statuses
- add storage of selected order status to local storage
- add console output for new events

**Comment by Mhera17** [comment]
Hello @eburck , @DomiKoch 
just for an update.
I have connected a new build, and it crashed with an error in runtime, 
After removing lazy() it works. it might be some kind of internal incompatibility with Vite and preact. I'm trying to fix it

**Comment by Mhera17** [comment]
Hello @eburck @DomiKoch.
i have added v2 and created  PR https://github.com/trustedshops-public/connect-app-demo/pull/71.
but as I already said, it doesn't work correctly with lazy imports. So I did build:qa after deleting all lazy() imports from index.tsx in the dashboard folder.
